---
# you can use glob pattern
"**/*":
  - sinyoungP

".github/workflows/*.yml":
  - shufo2

# you can set multiple reviewers
".github/**/*.yml":
  - foo
  - bar

# you can set team reviewers (repo scope token required)
".github/**/*.md":
#  - team: baz
